import { useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import type { useVocabulary } from "@/lib/hooks/useVocabulary";
import { currentLevel, levelLabels, nextPracticeMode, statusLabels, targetLabels, targetLevel, targetMet, targetReason, testModes, vocabularyTypes, type TestMode, type VocabularyWord } from "@/lib/english/vocabulary";
import { playVocabularyAudio } from "./VocabularyPractice";

const button="min-h-11 rounded-lg border border-border px-3 py-2 text-sm disabled:opacity-40 hover:bg-sage-light/30";
const display = (v: string) => v.normalize("NFKC").replace(/\s+/g, " ").trim();
// A re-evaluation is a preview: the server recommends, the learner decides. Nothing is written
// until 采用建议 runs the normal edit path, which is what marks the target as manually chosen.
interface Recommendation { recommended_level: keyof typeof targetLabels; target_reason: string; current_level: string; curated: boolean }
export default function VocabularyCard({word:w,model,onTest}:{word:VocabularyWord;model:ReturnType<typeof useVocabulary>;onTest:(mode:TestMode)=>Promise<void>}) {
  const [error,setError]=useState("");
  const next=nextPracticeMode(w);
  const [mode,setMode]=useState<TestMode>(next.mode);
  const [editing,setEditing]=useState(false);
  const [type,setType]=useState(w.type);
  const [target,setTarget]=useState(w.target_level||"R1");
  const [meaning,setMeaning]=useState(w.meaning);
  const [pos,setPos]=useState(w.pos);
  const [rec,setRec]=useState<Recommendation|null>(null);
  const attempted=useRef(false);
  const e=w.enrichment;
  const errors=useQuery({queryKey:["vocabulary-errors",w.id,w.version],enabled:w.error_count>0,queryFn:async()=>{
    const {data,error}=await supabase.from("vocabulary_errors").select("*").eq("word_id",w.id).order("created_at",{ascending:false}).limit(50);
    if(error) throw error;return data;
  }});
  async function run(fn:()=>Promise<unknown>){setError("");try{await fn();}catch(e){setError((e as Error).message||"操作失败，请重试");}}
  // Only enrich opened cards, once per mount; a failed call never creates an automatic retry loop.
  useEffect(()=>{if(!w.archived && e?.schema_version!==2 && !attempted.current){attempted.current=true;void run(()=>model.ai.mutateAsync({action:"enrich",wordId:w.id}));}},[w.id]);
  useEffect(()=>setMode(next.mode),[next.mode]);
  useEffect(()=>{if(!editing){setType(w.type);setTarget(w.target_level||"R1");setMeaning(w.meaning);setPos(w.pos);}},[w.type,w.target_level,w.meaning,w.pos,editing]);
  const pending=model.ai.isPending||model.question.isPending||model.edit.isPending||model.archive.isPending;
  const ladder=(Object.keys(targetLabels) as (keyof typeof targetLabels)[]);
  const goal=ladder.indexOf(targetLevel(w));
  const goalMet=targetMet(w);
  const stepMode=(l:keyof typeof targetLabels):TestMode=>l==="R2"&&w.type==="collocation" ? "collocation" : l;
  const stepDone=(l:keyof typeof targetLabels)=>(w.mastery?.[l]?.passes||0)>=(l==="P1"||l==="P2" ? 2 : 1);
  const recommended=(e?.recommended_level && e.recommended_level!=="R0" ? e.recommended_level : targetLevel(w));
  return <article className="rounded-lg bg-card p-5 sm:p-6 space-y-7 min-w-0 [overflow-wrap:anywhere]">
    <header><div className="flex justify-between items-start gap-3"><h2 className="text-3xl font-semibold break-all">{w.word}</h2><button className={button + " shrink-0"} onClick={()=>playVocabularyAudio(w.word,()=>{},setError)}>发音</button></div>{e?.pronunciation&&<p className="text-sm text-ink-light mt-2">{e.pronunciation}</p>}<p className="text-sm text-ink-light mt-3">{w.pos} · {vocabularyTypes[w.type]}</p><p className="text-xs text-ink-light mt-2">当前：{levelLabels[currentLevel(w)]} · 目标：{targetLabels[targetLevel(w)]} · {statusLabels[w.archived?"archived":w.status]} · 听力{{unknown:"未测试",weak:"薄弱",learning:"巩固中",stable:"稳定"}[w.listening_status||"unknown"]}</p></header>
    {error && <p role="alert" className="text-red-700 text-sm">{error}</p>}
    <section className="space-y-3 text-sm"><h3 className="font-semibold">核心释义</h3><p className="leading-relaxed">{w.meaning||e?.core_meaning||"资料未提供，见学习建议与来源原文"}</p>{w.type==="familiar"&&e&&<div className="rounded-lg bg-sage-light/35 p-4 space-y-3"><div><p className="text-xs text-ink-light">Known meaning · 熟悉义</p><p className="mt-1">{e.known_meaning||e.core_meaning}</p></div><div><p className="text-xs text-sage-deep">TEM8 · 语境义</p><p className="mt-1 font-medium">{e.tem8_meaning}</p></div></div>}</section>
    {e ? <>
      <section className="space-y-3 text-sm leading-relaxed"><h3 className="font-semibold">AI 学习卡</h3><p>{e.english_definition}</p>{w.type!=="familiar"&&<p>专八语境：{e.tem8_meaning}</p>}{e.trigger&&<p>识别线索：{e.trigger}</p>}{e.register&&<p>语域：{e.register}</p>}{e.writing_use&&<p>写作用法：{e.writing_use}</p>}{e.translation_use&&<p>翻译用法：{e.translation_use}</p>}<p className="text-xs text-ink-lighter">建议 {targetLabels[recommended]} · 学习价值 {{high:"高",medium:"中",low:"低"}[e.value]}</p></section>
      {(e.collocations.length>0||!!e.synonyms?.length)&&<section className="space-y-3 text-sm"><h3 className="font-semibold">搭配与近义表达</h3><ul className="flex flex-wrap gap-2">{e.collocations.map((c,i)=><li key={i} className="rounded-lg bg-sage-light/40 px-3 py-2">{c}</li>)}</ul>{!!e.synonyms?.length&&<p className="text-ink-light">近义表达：{e.synonyms.join(" / ")}</p>}</section>}
      {(e.examples.length>0||e.contrast_example)&&<section className="space-y-3 text-sm"><h3 className="font-semibold">例句</h3>{e.examples.map((ex,i)=><blockquote key={i} className="rounded-lg bg-ink/5 p-4 leading-relaxed">{ex}</blockquote>)}{e.contrast_example&&<div className="rounded-lg bg-ink/5 p-4"><p className="text-xs text-ink-light mb-2">对比例句</p><p>{e.contrast_example}</p></div>}</section>}
      {e.trap&&<section className="space-y-2 text-sm"><h3 className="font-semibold">易错点</h3><p className="leading-relaxed">{e.trap}</p></section>}
    </> : <section className="text-sm space-y-3"><h3 className="font-semibold">AI 学习卡</h3><p>{model.ai.isPending ? "正在生成学习卡…" : "学习卡尚未生成。原资料已保留。"}</p><button className={button} disabled={pending} onClick={()=>void run(()=>model.ai.mutateAsync({action:"enrich",wordId:w.id}))}>生成／重试</button></section>}
    <details className="text-sm"><summary className="cursor-pointer min-h-11 flex items-center font-medium">来源 × {w.sources.length}</summary>{w.sources.map((s,i)=><div key={i} className="mt-3 rounded-lg bg-ink/5 p-4"><p className="text-sm">{s.name}</p><p className="text-xs text-ink-light mt-1">原形式：{display(s.original)}</p><details className="mt-2"><summary className="cursor-pointer min-h-11 flex items-center text-sage-deep">查看原文</summary><blockquote className="whitespace-pre-wrap break-words max-h-80 overflow-auto mt-2 leading-relaxed">{display(s.context)}</blockquote></details></div>)}</details>
    {!w.archived && <section className="border-t border-border pt-4 space-y-3"><h3 className="font-medium text-sm">学习目标</h3><p className="text-sm font-medium">{targetLabels[targetLevel(w)]}</p><p className="text-xs text-ink-light">原因：{targetReason(w)}</p><ol className="text-sm space-y-1">{ladder.slice(0,goal+1).map(l=><li key={l} className={stepDone(l)?"text-sage-deep":"text-ink-light"}>{stepDone(l)?"✓":next.mode===stepMode(l)?"→":"○"} {targetLabels[l]}</li>)}<li className={goalMet?"text-sage-deep":"text-ink-lighter"}>{goalMet?"✓":"○"} 完成{goalMet?"（已达标，只按复习计划巩固）":""}</li></ol><button disabled={pending||!e} className="min-h-11 w-full sm:w-auto bg-sage-deep text-white rounded-lg px-4 py-2 text-sm disabled:opacity-40" onClick={()=>void run(()=>onTest(next.mode))}>{model.question.isPending ? "正在准备题目…" : next.done ? "开始复习" : "继续学习"}</button><p className="text-xs text-ink-lighter">下一步：{testModes[next.mode]} · {next.reason}。80 分通过；达到学习目标后不再升级，只做间隔复习。</p><details className="text-xs text-ink-light"><summary className="cursor-pointer min-h-11 flex items-center">更多</summary><label className="block mt-2">自定义测试<select aria-label="自定义测试" value={mode} onChange={ev=>setMode(ev.target.value as TestMode)} className="mt-1 block rounded-lg border border-border p-2 w-full bg-card">{Object.entries(testModes).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button disabled={pending||!e} className={`${button} mt-2`} onClick={()=>void run(()=>onTest(mode))}>用所选类型出题</button></details></section>}
    {w.error_count>0&&<details className="text-sm"><summary>错因与再测 · 累计 {w.error_count} 次</summary>{errors.isError&&<p role="alert">错因加载失败<button onClick={()=>void errors.refetch()}>重试</button></p>}{errors.data?.map(err=><div key={err.id} className="mt-3 border-t border-border pt-3 space-y-1"><p className="text-xs text-ink-lighter">{err.mode||"历史自评"} · {err.resolved_at ? "已通过跨日再测" : "待再测"}</p><p>当时理解：{err.interpretation}</p><p>实际含义：{err.actual_meaning}</p><p>错因：{err.root_cause}</p><p>迁移规则：{err.transferable_rule}</p>{err.mode&&!err.resolved_at&&<button disabled={pending||!e} className={`${button} mt-2`} onClick={()=>void run(()=>onTest(err.mode as TestMode))}>用新语境再测</button>}</div>)}</details>}
    <div className="flex flex-wrap gap-2 border-t border-border pt-3"><button className={button} disabled={pending} onClick={()=>void run(async()=>setRec(await model.ai.mutateAsync({action:"recommend",wordId:w.id}) as unknown as Recommendation))}>重新评估学习目标</button><button className={button} disabled={pending} onClick={()=>setEditing(!editing)}>修订分类／学习目标</button><button className={button} disabled={pending} onClick={()=>void run(()=>model.archive.mutateAsync({id:w.id,archived:!w.archived}))}>{w.archived ? "恢复学习" : "暂不学习，归档"}</button></div>
    {rec&&<div className="rounded-lg bg-sage-light/30 p-4 space-y-2 text-sm"><p>系统建议：{targetLabels[rec.recommended_level]}</p><p className="text-xs text-ink-light">原因：{rec.target_reason||"暂无说明"}</p>{rec.curated&&rec.recommended_level!==targetLevel(w)&&<p className="text-xs text-ink-lighter">当前目标由你手动设定，只有确认后才会替换。</p>}<div className="flex flex-wrap gap-2"><button className={button} disabled={pending} onClick={()=>void run(async()=>{await model.edit.mutateAsync({word:w,type,target:rec.recommended_level,meaning,pos});setRec(null);await model.ai.mutateAsync({action:"enrich",wordId:w.id});})}>采用建议</button><button className={button} disabled={pending} onClick={()=>setRec(null)}>保留当前目标</button></div></div>}
    {editing&&<form className="space-y-3 text-sm" onSubmit={ev=>{ev.preventDefault();void run(async()=>{await model.edit.mutateAsync({word:w,type,target,meaning,pos});setEditing(false);await model.ai.mutateAsync({action:"enrich",wordId:w.id});});}}><p className="text-xs text-ink-light">原文来源保留。修订后重新加工学习卡，旧题不会继续用于测试。</p><label className="block">分类<select value={type} onChange={ev=>setType(ev.target.value as typeof type)} className="block w-full border border-border rounded-lg p-2 mt-1">{Object.entries(vocabularyTypes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="block">学习目标<select value={target} onChange={ev=>setTarget(ev.target.value as typeof target)} className="block w-full border border-border rounded-lg p-2 mt-1">{(["R1","R2","P1","P2"] as const).map(v=><option key={v} value={v}>{targetLabels[v]}</option>)}</select></label><p className="text-xs text-ink-lighter">系统推荐：{targetLabels[recommended]} · {targetReason(w)}。手动修改后不会被自动加工覆盖。</p><label className="block">词性<input value={pos} maxLength={50} onChange={ev=>setPos(ev.target.value)} className="block w-full border border-border rounded-lg p-2 mt-1"/></label><label className="block">个人修订释义<textarea value={meaning} maxLength={3000} onChange={ev=>setMeaning(ev.target.value)} className="block w-full border border-border rounded-lg p-2 mt-1"/></label><button className={button} disabled={pending}>保存修订</button></form>}
  </article>;
}
