import { testModes, type VocabularyAttempt, type VocabularyDashboard, type VocabularyWord } from "@/lib/english/vocabulary";
export default function VocabularyProgress({dashboard,history,words,onWord}:{dashboard?:VocabularyDashboard;history:VocabularyAttempt[];words:VocabularyWord[];onWord:(id:string)=>void}) {
  return <section className="space-y-5">
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{["R1","R2","P1","P2"].map(level=><div key={level} className="rounded-lg border border-border p-4"><p className="text-2xl font-semibold">{words.filter(w=>!w.archived&&w.level===level).length}</p><p className="text-xs text-ink-light mt-1">{level} 当前掌握</p></div>)}</div>
    <p className="text-sm text-ink-light">累计测试 {dashboard?.attempts||0} 次 · 今日已测试 {dashboard?.today_completed||0} 词 · 未解决错误 {dashboard?.open_errors||0} 条</p>
    <div className="overflow-x-auto"><table className="w-full text-sm text-left"><caption className="text-left font-semibold mb-3">分层能力</caption><thead><tr className="border-b border-border"><th className="py-2">训练类型</th><th>测试次数</th><th>平均分</th><th>通过率</th></tr></thead><tbody>{dashboard?.modes.map(row=><tr key={row.mode} className="border-b border-border"><td className="py-3">{testModes[row.mode]}</td><td>{row.attempts}</td><td>{row.average_score}</td><td>{row.attempts ? Math.round(row.passed/row.attempts*100) : 0}%</td></tr>)}</tbody></table></div>
    <details className="border border-border rounded-lg p-4"><summary>近 30 天学习记录</summary><div className="flex flex-wrap gap-2 mt-3">{dashboard?.days.map(day=><div key={day.day} className="rounded-lg bg-sage-light/30 p-3 text-xs"><p>{day.day}</p><p className="mt-1">{day.passed}/{day.attempts} 次通过</p></div>)}{!dashboard?.days.length&&<p className="text-sm text-ink-lighter">完成首次测试后开始记录。</p>}</div></details>
    <h2 className="font-semibold">最近 100 次测试</h2>
    {history.map(item=><details key={item.id} className="rounded-lg border border-border p-4 text-sm"><summary className="cursor-pointer">{words.find(w=>w.id===item.word_id)?.word||"词条"} · {testModes[item.mode]} · {item.score} 分 · {item.day}</summary><div className="space-y-2 mt-3"><p>我的答案：{item.answer}</p><p>{item.feedback?.explanation}</p><p>参考答案：{item.feedback?.expected_answer}</p>{item.feedback?.root_cause&&<p>错因：{item.feedback.root_cause}</p>}<button className="underline text-sage-deep" onClick={()=>onWord(item.word_id)}>打开词卡与再测</button></div></details>)}
  </section>;
}
