import { describe,expect,it } from "vitest";
import { validateQuestion,publicQuestion,deterministicGrade,validateGrade,type Question } from "../../supabase/functions/tem8-vocabulary-agent/practice";
import { dailyVocabularyQueue,nextPracticeMode,type VocabularyWord } from "@/lib/english/vocabulary";
const q:Question={prompt:"New evidence qualifies the conclusion. What does qualifies mean?",options:["limits","rejects","confirms","explains"],correct_index:0,expected_answer:"limits",explanation:"限定结论",trigger:"qualify + statement",audio_text:"",rubric:"correct sense"};
describe("TEM8 graded practice",()=>{
  it("never sends objective answer keys before submission",()=>{const result=publicQuestion(q,"R2");expect(result).not.toHaveProperty("correct_index");expect(result).not.toHaveProperty("expected_answer");expect(result).not.toHaveProperty("explanation");});
  it("rejects invalid choices and marks choice answers deterministically",()=>{expect(deterministicGrade(q,"R2","0")?.score).toBe(100);expect(deterministicGrade(q,"R2","1")?.score).toBe(0);expect(()=>deterministicGrade(q,"R2","99")).toThrow();});
  it("rejects duplicate options, invalid answer indices and malformed cloze questions",()=>{expect(()=>validateQuestion({...q,correct_index:4},"R2")).toThrow();expect(()=>validateQuestion({...q,options:["a","a","b","c"]},"R1")).toThrow();expect(()=>validateQuestion(q,"collocation")).toThrow();});
  it("grades listening independently and normalizes punctuation/case",()=>{const audio={...q,options:[],correct_index:null,audio_text:"pose a threat",expected_answer:"pose a threat"};expect(validateQuestion(audio,"listening")).toBeTruthy();expect(deterministicGrade(audio,"listening","Pose a threat.")?.score).toBe(100);expect(deterministicGrade(audio,"listening","post a threat")?.error_type).toBe("listening_recognition");});
  it("routes production to semantic grading and caps wrong-sense scores",()=>{expect(deterministicGrade(q,"P2","answer")).toBeNull();const grade={score:95,explanation:"Wrong meaning",error_type:"meaning",root_cause:"Wrong sense",transferable_rule:"Check object",corrected_answer:"corrected",criteria:{meaning:20,grammar:100,collocation:100,register:100}};expect(validateGrade(grade,q).score).toBe(59);expect(()=>validateGrade({...grade,score:NaN},q)).toThrow();});
  it("does not create new queue entries after planned words are completed",()=>{const base={id:"planned",sources:[],error_count:0,type:"new",status:"inbox"} as unknown as VocabularyWord;const plan={user_id:"u",day:"2026-09-10",target:1,new_ids:["planned"],familiar_ids:[],production_ids:[]};const now=Date.parse("2026-09-10");expect(dailyVocabularyQueue([{...base,due_at:"2027-01-01"},{...base,id:"unplanned"}],plan,now)).toHaveLength(0);expect(dailyVocabularyQueue([{...base,id:"due",due_at:"2020-01-01"}],plan,now)).toHaveLength(1);});
  it("requires lower-skill evidence before suggesting production",()=>{const w={target_level:"P2",mastery:{}} as VocabularyWord;expect(nextPracticeMode(w).mode).toBe("R1");expect(nextPracticeMode({...w,mastery:{R1:{passes:1,last_day:"",score:100},R2:{passes:1,last_day:"",score:100}}}).mode).toBe("P1");});
});
