import { useState, useRef, useEffect } from "react";
import { useLocation } from "wouter";
import { getGreeting, getDateLabel, today } from "@/lib/utils";
import {
  Lightbulb, CheckSquare, Clock, Calendar, Trophy, Zap, Sparkles, Settings, Loader2,
  CheckCircle2, Send, FileText, ChevronRight, BookOpen, Dumbbell, GraduationCap, Heart, ArrowRight,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useTodayBrief, useGenerateDailyBrief, useBriefFeedback } from "@/lib/hooks/useReflection";
import { useDashboardStats } from "@/lib/hooks/useDashboard";
import { useUpcomingTasks, useToggleTaskComplete } from "@/lib/hooks/usePlan";
import { useHabitsWithToday, useToggleHabitCompletion, useHabitWeeklyStats, useHabitAnalysis, formatFrequency, type HabitWithRecord } from "@/lib/hooks/useHabit";
import { useCreateIdea } from "@/lib/hooks/useLifeTrace";
import {
  useWaterToday, useAddWater, useDeleteWater,
  useDailyChecklist, useInitChecklist, useToggleChecklistItem,
  useGenerateChecklistTips, useInsertChecklistAiItems,
  useFoodRecords, useWorkoutRecords,
} from "@/lib/hooks/useHealth";
import type { DailyBrief } from "@/lib/types";
import {
  StatusCard, ModuleCard, WaterTracker, DailyHealthChecklist,
  TodayHabits, TodaySchedule, DailyBriefCard, TimelineSection,
} from "@/components/home";

const QUICK_ACTIONS = [
  { key: "ideas", label: "灵感库", icon: Lightbulb, color: "bg-accent-warm/10 text-accent-warm", path: "/ideas" },
  { key: "daily", label: "每日日记", icon: FileText, color: "bg-accent-rose/10 text-accent-rose", path: "/life-trace/daily" },
  { key: "review", label: "每日复盘", icon: Sparkles, color: "bg-sage-light text-sage-deep", path: "/review" },
] as const;

const PRIORITY_LABELS: Record<string, string> = { high: "高", medium: "中", low: "低" };

export default function Home() {
  const [, navigate] = useLocation();
  const greeting = getGreeting();
  const dateStr = today();
  const dateLabel = getDateLabel(dateStr);
  const isEvening = new Date().getHours() >= 18;

  const { data: brief, isLoading: loadingBrief } = useTodayBrief();
  const generateBrief = useGenerateDailyBrief();
  const { data: stats, isLoading: loadingStats } = useDashboardStats();
  const { data: upcomingTasks } = useUpcomingTasks(7);
  const { data: habitsWithToday } = useHabitsWithToday();
  const toggleHabitCompletion = useToggleHabitCompletion();
  const toggleTaskComplete = useToggleTaskComplete();
  const briefFeedback = useBriefFeedback();
  const createIdea = useCreateIdea();
  const { data: habitWeeklyStats } = useHabitWeeklyStats(2);
  const { data: habitAnalysis } = useHabitAnalysis();
  const { data: waterToday } = useWaterToday(dateStr);
  const addWater = useAddWater();
  const deleteWater = useDeleteWater();
  const { data: checklist } = useDailyChecklist(dateStr);
  const initChecklist = useInitChecklist();
  const toggleChecklistItem = useToggleChecklistItem();
  const generateTips = useGenerateChecklistTips();
  const insertAiItems = useInsertChecklistAiItems();
  const { data: foodToday } = useFoodRecords(dateStr);
  const { data: workoutToday } = useWorkoutRecords(dateStr);

  // Auto-init checklist on first load
  const checklistInited = useRef(false);
  useEffect(() => {
    if (!checklist && !checklistInited.current) {
      checklistInited.current = true;
      initChecklist.mutate(dateStr, {
        onSuccess: (data) => {
          const checklistId = data.id as string;
          generateTips.mutate(
            { date: dateStr, checklistId },
            {
              onSuccess: (tips) => {
                insertAiItems.mutate({ date: dateStr, checklistId, tips: tips.tips });
              },
            },
          );
        },
      });
    }
  }, [checklist, dateStr]);

  const briefData = brief as DailyBrief | null;
  const [feedbackSent, setFeedbackSent] = useState(false);
  const [quickCaptureText, setQuickCaptureText] = useState("");
  const [captureSaved, setCaptureSaved] = useState(false);

  // Auto-generate daily brief on first load
  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    if (!brief && !loadingBrief && !generateBrief.isPending && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      generateBrief.mutate();
    }
  }, [brief, loadingBrief]);

  const handleBriefFeedback = (rating: "helpful" | "not_helpful") => {
    if (!briefData?.id || feedbackSent) return;
    briefFeedback.mutate({ briefId: briefData.id, rating });
    setFeedbackSent(true);
  };

  const handleQuickCapture = () => {
    const text = quickCaptureText.trim();
    if (!text || createIdea.isPending) return;
    createIdea.mutate(
      { content: text, category: "quick_capture" },
      {
        onSuccess: () => {
          setQuickCaptureText("");
          setCaptureSaved(true);
          setTimeout(() => setCaptureSaved(false), 2000);
        },
      },
    );
  };

  const handleTaskToggle = (taskId: string, taskStatus: string) => {
    toggleTaskComplete.mutate({ id: taskId, currentStatus: taskStatus });
  };

  return (
    <div className="space-y-5">
      {/* Header */}
      <header className="flex items-center justify-between">
        <div>
          <p className="text-sm text-ink-lighter">{dateLabel}</p>
          <h1 className="text-2xl font-semibold tracking-tight mt-0.5">
            {greeting}，Nancy
          </h1>
          <p className="text-sm text-ink-lighter mt-1">今天也请按自己的节奏来</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => navigate("/settings")}
            className="h-11 w-11 rounded-xl bg-card border border-border flex items-center justify-center hover:bg-card-hover transition-colors"
            title="设置"
          >
            <Settings size={18} className="text-ink-light" />
          </button>
          <div className="h-11 w-11 rounded-xl bg-sage-light flex items-center justify-center">
            <Sparkles size={20} className="text-sage-deep" />
          </div>
        </div>
      </header>

      {/* ── First Screen: Status Cards ── */}
      <section className="grid grid-cols-3 gap-3">
        <StatusCard
          icon={CheckSquare}
          label="今日任务"
          value={loadingStats ? "..." : `${stats?.tasks.completed ?? 0}/${stats?.tasks.total ?? 0}`}
          sub={stats?.tasks.total ? `待完成 ${stats.tasks.pending.length} 项` : "暂无任务"}
          color="text-accent-sky"
          bg="bg-accent-sky/5"
          path="/plan?tab=tasks"
        />
        <StatusCard
          icon={Trophy}
          label="习惯完成"
          value={loadingStats ? "..." : `${stats?.habits.completed ?? 0}/${stats?.habits.total ?? 0}`}
          sub={stats?.habits.streak ? `连续 ${stats.habits.streak} 天` : "今日暂无记录"}
          color="text-accent-warm"
          bg="bg-accent-warm/5"
          path="/plan?tab=habits"
        />
        <StatusCard
          icon={Clock}
          label="待复习"
          value={loadingStats ? "..." : `${stats?.reviews.due ?? 0}`}
          sub="英语表达"
          color="text-sage-deep"
          bg="bg-sage-light"
          path="/english/review"
        />
      </section>

      {/* ── First Screen: Today's Focus Tasks ── */}
      {stats && (stats.timeline.inProgress.length > 0 || stats.timeline.pending.length > 0) && (
        <TodaySchedule
          stats={stats}
          onToggleTask={handleTaskToggle}
          isToggling={toggleTaskComplete.isPending}
        />
      )}

      {/* ── First Screen: Quick Capture ── */}
      <div className="flex items-center gap-2 bg-white border border-sage-light/30 rounded-2xl px-4 py-2.5 shadow-sm">
        <Zap size={16} className="text-sage-deep shrink-0" />
        <input
          type="text"
          value={quickCaptureText}
          onChange={(e) => setQuickCaptureText(e.target.value)}
          onKeyDown={(e) => { if (e.key === "Enter") handleQuickCapture(); }}
          placeholder="快速记录想法、任务或灵感..."
          className="flex-1 bg-transparent text-sm text-ink placeholder:text-ink-lighter outline-none"
        />
        {captureSaved ? (
          <CheckCircle2 size={16} className="text-emerald-500 shrink-0" />
        ) : (
          <button
            onClick={handleQuickCapture}
            disabled={!quickCaptureText.trim() || createIdea.isPending}
            className="shrink-0 text-sage-deep disabled:text-ink-lighter hover:text-sage-deep/70 transition-colors"
          >
            {createIdea.isPending ? (
              <Loader2 size={16} className="animate-spin" />
            ) : (
              <Send size={16} />
            )}
          </button>
        )}
      </div>

      {/* ── Second Screen: Today's Habits ── */}
      {habitsWithToday && (habitsWithToday as HabitWithRecord[]).length > 0 && (
        <TodayHabits
          habits={habitsWithToday as HabitWithRecord[]}
          onToggle={(habitId) => toggleHabitCompletion.mutate(habitId, {
            onError: (err) => { console.error("Habit toggle failed:", err); },
          })}
          isToggling={toggleHabitCompletion.isPending}
          weeklyStats={habitWeeklyStats || []}
          analysis={habitAnalysis}
          formatFreq={formatFrequency}
        />
      )}

      {/* ── Second Screen: AI Daily Brief (collapsible) ── */}
      {loadingBrief || generateBrief.isPending ? (
        <div className="bg-card rounded-2xl border border-sage-light/30 p-6 flex items-center justify-center gap-3">
          <Loader2 size={18} className="animate-spin text-sage-deep" />
          <span className="text-sm text-ink-light">
            {generateBrief.isPending ? "正在生成今日简报..." : "加载中..."}
          </span>
        </div>
      ) : briefData ? (
        <DailyBriefCard
          key={briefData.id}
          brief={briefData}
          onRegenerate={() => { generateBrief.mutate(); setFeedbackSent(false); }}
          isRegenerating={generateBrief.isPending}
          onFeedback={handleBriefFeedback}
          feedbackSent={feedbackSent}
          feedbackPending={briefFeedback.isPending}
        />
      ) : null}

      {/* ── Third Screen: Timeline (collapsible, aggregated) ── */}
      {stats && <TimelineSection stats={stats} />}

      {/* ── Water Tracker ── */}
      <WaterTracker
        waterToday={waterToday}
        onAdd={(amount) => addWater.mutate({ date: dateStr, amount_ml: amount })}
        onDelete={(id) => deleteWater.mutate({ id, date: dateStr })}
        isAdding={addWater.isPending}
      />

      {/* ── Daily Health Checklist ── */}
      <DailyHealthChecklist
        checklist={checklist}
        waterToday={waterToday}
        foodToday={foodToday}
        workoutToday={workoutToday}
        onToggleItem={(itemId, completed) =>
          toggleChecklistItem.mutate({ itemId, isCompleted: completed, date: dateStr })
        }
        onRegenerate={() => {
          if (!checklist) return;
          generateTips.mutate(
            { date: dateStr, checklistId: checklist.id },
            {
              onSuccess: (tips) => {
                insertAiItems.mutate({ date: dateStr, checklistId: checklist.id, tips: tips.tips });
              },
            },
          );
        }}
        isRegenerating={generateTips.isPending || insertAiItems.isPending}
        isInitializing={initChecklist.isPending}
      />

      {/* ── Evening Reflection (after 18:00) ── */}
      {isEvening && (
        <section
          onClick={() => navigate("/review")}
          className="bg-gradient-to-br from-sage-light/10 to-indigo-50/30 border border-sage-light/30 rounded-2xl p-4 cursor-pointer hover:shadow-sm transition-all"
        >
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-xl bg-sage-light flex items-center justify-center shrink-0">
              <Sparkles size={18} className="text-sage-deep" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-semibold text-ink">晚间复盘</p>
              <p className="text-xs text-ink-light mt-0.5">
                今天完成了什么？AI 帮你生成成长洞察并进入长期记忆。
              </p>
            </div>
            <ChevronRight size={16} className="text-ink-lighter shrink-0" />
          </div>
        </section>
      )}

      {/* ── Quick Record ── */}
      <section>
        <h2 className="text-[13px] font-semibold text-ink mb-3">快速记录</h2>
        <div className="grid grid-cols-3 gap-2">
          {QUICK_ACTIONS.map((action) => {
            const IconComponent = action.icon;
            return (
              <button
                key={action.key}
                onClick={() => navigate(action.path)}
                className="flex flex-col items-center gap-1.5 py-3 rounded-2xl hover:bg-card-hover transition-colors active:scale-95"
              >
                <div className={cn("h-11 w-11 rounded-xl flex items-center justify-center", action.color)}>
                  <IconComponent size={20} />
                </div>
                <span className="text-[11px] text-ink-light leading-tight text-center">{action.label}</span>
              </button>
            );
          })}
        </div>
      </section>

      {/* ── Upcoming (next 7 days) ── */}
      {upcomingTasks && (upcomingTasks as Array<Record<string, unknown>>).length > 0 && (
        <section className="bg-gradient-to-br from-accent-sky/[0.03] to-white border border-accent-sky/10 rounded-2xl p-4">
          <div className="flex items-center gap-2 mb-3">
            <Calendar size={13} className="text-accent-sky" />
            <h2 className="text-xs font-semibold text-ink">即将到来</h2>
            <span className="text-[10px] text-ink-lighter">
              (未来7天 {">"} {(upcomingTasks as Array<Record<string, unknown>>).length} 项)
            </span>
          </div>
          <div className="space-y-1">
            {(upcomingTasks as Array<Record<string, unknown>>).slice(0, 6).map((t) => {
              const dueDate = t.due_date as string;
              if (!dueDate) return null;
              const daysUntil = Math.ceil((new Date(dueDate).getTime() - Date.now()) / 86400000);
              const isToday = daysUntil === 0;
              const isTomorrow = daysUntil === 1;
              const label = isToday ? "今天" : isTomorrow ? "明天" : `${daysUntil}天后`;

              return (
                <button
                  key={t.id as string}
                  onClick={() => navigate("/plan")}
                  className="w-full flex items-center gap-2.5 rounded-lg px-2.5 py-1.5 hover:bg-white/60 transition-colors text-left"
                >
                  <span className={cn(
                    "text-[10px] px-1.5 py-0.5 rounded-full font-medium shrink-0 min-w-[42px] text-center",
                    isToday ? "bg-accent-rose/10 text-accent-rose" :
                    isTomorrow ? "bg-accent-warm/10 text-accent-warm" : "bg-ink/5 text-ink-lighter",
                  )}>
                    {label}
                  </span>
                  <span className="text-xs text-ink truncate flex-1">{t.title as string}</span>
                  <span className={cn(
                    "text-[10px] px-1 py-0.5 rounded font-medium shrink-0",
                    (t.priority as string) === "high" ? "bg-accent-rose/10 text-accent-rose" :
                    (t.priority as string) === "medium" ? "bg-amber-50 text-amber-600" : "bg-ink/5 text-ink-lighter",
                  )}>
                    {PRIORITY_LABELS[t.priority as string] || t.priority as string}
                  </span>
                  <ArrowRight size={10} className="text-ink-lighter shrink-0" />
                </button>
              );
            })}
          </div>
        </section>
      )}

      {/* ── Module Overview Cards ── */}
      <section>
        <h2 className="text-[13px] font-semibold text-ink mb-3">模块概览</h2>
        <div className="grid grid-cols-2 gap-3">
          <ModuleCard
            icon={BookOpen}
            label="English OS"
            stat={loadingStats ? "..." : `${stats?.reviews.due ?? 0} 待复习`}
            statDetail={`${stats?.reviews.totalExpressions ?? 0}+ 表达库`}
            color="bg-accent-sky/10"
            iconColor="text-accent-sky"
            path="/english"
          />
          <ModuleCard
            icon={Dumbbell}
            label="健康管理"
            stat={loadingStats ? "..." : stats?.habits.completed ? `今日已完成 ${stats.habits.completed} 项` : "今日未运动"}
            statDetail={stats?.habits.streak ? `${stats.habits.streak} 天连续` : "0 天连续"}
            color="bg-sage-light"
            iconColor="text-sage-deep"
            path="/health"
          />
          <ModuleCard
            icon={GraduationCap}
            label="考试学习"
            stat="IELTS"
            statDetail="暂无倒计时"
            color="bg-accent-warm/10"
            iconColor="text-accent-warm"
            path="/exam"
          />
          <ModuleCard
            icon={Heart}
            label="Life Trace"
            stat={loadingStats ? "..." : stats?.lifeTrace.journalToday ? `${stats.lifeTrace.journalToday} 条日记` : "今日未记录"}
            statDetail={stats?.lifeTrace.journalThisMonth ? `本月 ${stats.lifeTrace.journalThisMonth} 条` : "0 条日记"}
            color="bg-accent-rose/10"
            iconColor="text-accent-rose"
            path="/life-trace"
          />
        </div>
      </section>

      {/* Bottom spacing for mobile */}
      <div className="h-2" />
    </div>
  );
}
