import { useState, useRef, useEffect } from "react";
import { useLocation } from "wouter";
import { getGreeting, getDateLabel, today } from "@/lib/utils";
import {
  Lightbulb, CheckSquare, Clock, Trophy, Sparkles, Settings, FileText,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useTodayBrief, useGenerateDailyBrief, useBriefFeedback } from "@/lib/hooks/useReflection";
import { useDashboardStats } from "@/lib/hooks/useDashboard";
import { useTodayTasks, useToggleTaskComplete } from "@/lib/hooks/usePlan";
import { useHabitsWithToday, useToggleHabitCompletion, useHabitWeeklyStats, useHabitAnalysis, formatFrequency, type HabitWithRecord } from "@/lib/hooks/useHabit";
import { useImportantEvents } from "@/lib/hooks/useImportantEvent";
import {
  useWaterToday,
  useDailyChecklist, useInitChecklist,
  useGenerateChecklistTips, useInsertChecklistAiItems,
  useFoodRecords, useWorkoutRecords,
} from "@/lib/hooks/useHealth";
import type { DailyBrief } from "@/lib/types";
import {
  StatusCard, TodayHabits, TodaySchedule, DailyBriefCard,
  TimelineSection, ImportantEvents, BodyStatus,
} from "@/components/home";

const QUICK_ACTIONS = [
  { key: "ideas", label: "灵感库", icon: Lightbulb, color: "bg-accent-warm/10 text-accent-warm", path: "/ideas" },
  { key: "daily", label: "每日日记", icon: FileText, color: "bg-accent-rose/10 text-accent-rose", path: "/life-trace/daily" },
  { key: "review", label: "每日复盘", icon: Sparkles, color: "bg-sage-light text-sage-deep", path: "/review" },
] as const;

export default function Home() {
  const [, navigate] = useLocation();
  const greeting = getGreeting();
  const dateStr = today();
  const dateLabel = getDateLabel(dateStr);

  const { data: brief, isLoading: loadingBrief } = useTodayBrief();
  const generateBrief = useGenerateDailyBrief();
  const { data: stats, isLoading: loadingStats } = useDashboardStats();
  const { data: todayTasks } = useTodayTasks();
  const toggleTaskComplete = useToggleTaskComplete();
  const briefFeedback = useBriefFeedback();
  const { data: habitsWithToday } = useHabitsWithToday();
  const toggleHabitCompletion = useToggleHabitCompletion();
  const { data: habitWeeklyStats } = useHabitWeeklyStats(2);
  const { data: habitAnalysis } = useHabitAnalysis();
  const { data: importantEvents } = useImportantEvents();
  const { data: waterToday } = useWaterToday(dateStr);
  const initChecklist = useInitChecklist();
  const generateTips = useGenerateChecklistTips();
  const insertAiItems = useInsertChecklistAiItems();
  const { data: checklist } = useDailyChecklist(dateStr);
  const { data: foodToday } = useFoodRecords(dateStr);
  const { data: workoutToday } = useWorkoutRecords(dateStr);

  const briefData = brief as DailyBrief | null;
  const [feedbackSent, setFeedbackSent] = useState(false);

  // Auto-init checklist on first load
  const checklistInited = useRef(false);
  useEffect(() => {
    if (!checklist && !checklistInited.current) {
      checklistInited.current = true;
      initChecklist.mutate(dateStr, {
        onSuccess: (data) => {
          const checklistId = data.id as string;
          generateTips.mutate(
            { date: dateStr, checklistId },
            {
              onSuccess: (tips) => {
                insertAiItems.mutate({ date: dateStr, checklistId, tips: tips.tips });
              },
            },
          );
        },
      });
    }
  }, [checklist, dateStr]);

  // Auto-generate daily brief on first load
  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    if (!brief && !loadingBrief && !generateBrief.isPending && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      generateBrief.mutate();
    }
  }, [brief, loadingBrief]);

  const handleBriefFeedback = (rating: "helpful" | "not_helpful") => {
    if (!briefData?.id || feedbackSent) return;
    briefFeedback.mutate({ briefId: briefData.id, rating });
    setFeedbackSent(true);
  };

  const handleTaskToggle = (taskId: string, taskStatus: string) => {
    toggleTaskComplete.mutate({ id: taskId, currentStatus: taskStatus });
  };

  const isGeneratingBrief = loadingBrief || generateBrief.isPending;

  return (
    <div className="space-y-5">
      {/* Header */}
      <header className="flex items-center justify-between">
        <div>
          <p className="text-sm text-ink-lighter">{dateLabel}</p>
          <h1 className="text-2xl font-semibold tracking-tight mt-0.5">
            {greeting}，Nancy
          </h1>
          <p className="text-sm text-ink-lighter mt-1">今天也请按自己的节奏来</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => navigate("/settings")}
            className="h-11 w-11 rounded-xl bg-card border border-border flex items-center justify-center hover:bg-card-hover transition-colors"
            title="设置"
          >
            <Settings size={18} className="text-ink-light" />
          </button>
          <div className="h-11 w-11 rounded-xl bg-sage-light flex items-center justify-center">
            <Sparkles size={20} className="text-sage-deep" />
          </div>
        </div>
      </header>

      {/* ── Status Dashboard (3 cards) ── */}
      <section className="grid grid-cols-3 gap-3">
        <StatusCard
          icon={CheckSquare}
          label="今日任务"
          value={loadingStats ? "..." : `${stats?.tasks.completed ?? 0}/${stats?.tasks.total ?? 0}`}
          sub={stats?.tasks.total ? `待完成 ${stats.tasks.pending.length} 项` : "暂无任务"}
          color="text-accent-sky"
          bg="bg-accent-sky/5"
          path="/plan?tab=tasks"
        />
        <StatusCard
          icon={Trophy}
          label="今日习惯"
          value={loadingStats ? "..." : `${stats?.habits.completed ?? 0}/${stats?.habits.total ?? 0}`}
          sub={stats?.habits.streak ? `连续 ${stats.habits.streak} 天` : "今日暂无记录"}
          color="text-accent-warm"
          bg="bg-accent-warm/5"
          path="/plan?tab=habits"
        />
        <StatusCard
          icon={Clock}
          label="今日学习"
          value={loadingStats ? "..." : `${stats?.reviews.due ?? 0} 待复习`}
          sub={stats?.speaking.minutesToday ? `口语 ${stats.speaking.minutesToday} 分钟` : `表达库 ${stats?.reviews.totalExpressions ?? 0}+`}
          color="text-sage-deep"
          bg="bg-sage-light"
          path="/english/review"
        />
      </section>

      {/* ── Important Events ── */}
      <ImportantEvents events={importantEvents} />

      {/* ── Quick Record (3 buttons, only entry point) ── */}
      <section>
        <div className="grid grid-cols-3 gap-2">
          {QUICK_ACTIONS.map((action) => {
            const IconComponent = action.icon;
            return (
              <button
                key={action.key}
                onClick={() => navigate(action.path)}
                className="flex flex-col items-center gap-1.5 py-3 rounded-2xl hover:bg-card-hover transition-colors active:scale-95"
              >
                <div className={cn("h-11 w-11 rounded-xl flex items-center justify-center", action.color)}>
                  <IconComponent size={20} />
                </div>
                <span className="text-[11px] text-ink-light leading-tight text-center">{action.label}</span>
              </button>
            );
          })}
        </div>
      </section>

      {/* ── Today's Focus Tasks ── */}
      <TodaySchedule
        tasks={todayTasks}
        onToggleTask={handleTaskToggle}
        isToggling={toggleTaskComplete.isPending}
      />

      {/* ── Today's Habits (compact) ── */}
      {habitsWithToday && (habitsWithToday as HabitWithRecord[]).length > 0 && (
        <TodayHabits
          habits={habitsWithToday as HabitWithRecord[]}
          onToggle={(habitId) => toggleHabitCompletion.mutate(habitId, {
            onError: (err) => { console.error("Habit toggle failed:", err); },
          })}
          isToggling={toggleHabitCompletion.isPending}
          weeklyStats={habitWeeklyStats || []}
          formatFreq={formatFrequency}
        />
      )}

      {/* ── Body Status (summary only) ── */}
      <BodyStatus
        waterTotal={waterToday?.total_ml}
        waterGoal={waterToday?.goal_ml}
        foodCount={(foodToday as unknown[])?.length ?? 0}
        workoutDone={(workoutToday as unknown[])?.length > 0}
      />

      {/* ── AI Daily Brief (at bottom, handles all three states) ── */}
      <DailyBriefCard
        key={briefData?.id ?? "empty"}
        brief={briefData}
        onGenerate={() => { generateBrief.mutate(); setFeedbackSent(false); }}
        onRegenerate={() => { generateBrief.mutate(); setFeedbackSent(false); }}
        isGenerating={isGeneratingBrief}
        onFeedback={handleBriefFeedback}
        feedbackSent={feedbackSent}
        feedbackPending={briefFeedback.isPending}
      />

      {/* ── Timeline (collapsed, after brief) ── */}
      {stats && <TimelineSection stats={stats} />}

      {/* Bottom spacing */}
      <div className="h-2" />
    </div>
  );
}
